### ISSUE TITLE
Attachments & WP8

### ISSUE THREAD

**Issue by lehtiton** [katzer/cordova-plugin-email-composer#102]
Hi,

Are WP8 attachments supported with version 0.8.2 of email composer? 

I thought they are because of:
- There is a mention "[enhancement:] Support attachments on Windows Phone 8.1" in the release notes...
- There is a mention "The plugin may crash on WP8.1/Windows if an attachmant does not exist." in the documentation

However, I have some doubts since:
- I have not succeed to get the attachments working
- There is a mention "Attachments and HTML+CSS formatted body are not supported through the native API for Windows Phone 8.0 and Windows Phone 8.1 Silverlight" in the documentation.

So, can someone either explicit tell if it is possible to attach file with WP8 and this plugin or not?

This is how I got it working with Android and iOS. WP just opens the email but without the attachment.

                 var attachment = 'base64:' + pdfName + '//,' + arrayBufferToBase64(document);

                  cordova.plugins.email.open({
                        to:      to,
                        subject: subject,
                        body:    body,
                        attachments: [attachment],
                        isHtml: false
                    });

Any help is highly appreciated!

Br. Toni

**Comment by PKnittel** [comment]
It´s not possible to attach files on WP8 Platform. For WP 8.1-Development use the windows platform, wich supports file-attachments. WP platform will be removed with the next major-release.

**Comment by manoj529** [comment]
Any update on this as i'm still unable to attach any files in windows phone 8.1. I have checked the code and found that it "Not supported on WP8.0 and WP8.1 Silverlight".
Please let me know any work around for it.

**Comment by katzer** [comment]
@manoj529 As I've seen your message, attachments are only possible using the cordova-windows platform (Windows Universal Platform)

**Comment by manoj529** [comment]
Thank you for the reply @katzer . Actually i have some depencies on the project due to which we decided not to migrate to cordova windows or wup. so wondering any work around for existing plugin. 
Came across with a tutorial at 
http://developerpublish.com/windows-phone-8-1-and-windows-runtime-apps-how-to-2-send-emails-with-attachment-in-wp-8-1/
Trying to combine it with the code patch but could't make it working. now again trying to create a build as windows universal platform. 
I will share my findings once i upgrade and once again thank you for providing us the plugin.
