### ISSUE TITLE
Carriage returns (\n) get lost in windows email body

### ISSUE THREAD

**Issue by regnete** [katzer/cordova-plugin-email-composer#123]
Due to the fact, that the windows app email api has no support to pass in a (html) formatted body in, we at least have to provide the body content including line breaks (\n).

But the line breaks get lost when the body is passed to the email client app.

A Modification to line https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/windows/EmailComposerProxyImpl.js#L105 would help to avoid the problem:

Actual: `draft.body = body;`
Fixed: `draft.body = encodeURIComponent(body);`

Or you could encode each property which is appended to the mailto-uri in https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/windows/EmailComposerProxyImpl.js#L53 

Thank you for providoing such a great plugin!

**Comment by regnete** [comment]
Just an idea: Why not encode each property which is appended to the mailto-uri in https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/windows/EmailComposerProxyImpl.js#L53 ?

**Comment by regnete** [comment]
I created a pull request fixing this and other issues: 
https://github.com/katzer/cordova-plugin-email-composer/pull/129

**Comment by amihaylo** [comment]
I have a somewhat similar issue. When sending from an email client on my android to a work email, the format is perfect. However when I run the exact same app from my apple device and send an email, some newlines are not displayed which is a big problem since the emails are parsed after. Can I use encodeURIComponent as mentioned above to change the ios code?
