### ISSUE TITLE
the .isAvailable() method always return "true" in iOS

### ISSUE THREAD

**Issue by linkchiu** [katzer/cordova-plugin-email-composer#151]
the .isAvailable() method always return "true" in iOS. when the mail client has no any account set up. the .isAvaialble() method still return "true". Can we fixed it?

**Comment by shankari** [comment]
This is because of this code. If the mail client has no account setup, canSendMail = false, but withScheme = true, so after this if statement, canSendMail = true as well.

```
    if (TARGET_IPHONE_SIMULATOR && [scheme hasPrefix:@"mailto:"]) {
        canSendMail = true;
    } else {
        canSendMail = canSendMail||withScheme;
    }
```
Furthermore, calling `open()` in that case crashes the app.

I tried a fix in which I comment out that line, and the isAvailable callback is still not triggered correctly, but when `open()` is called, the cancel callback is invoked, and the app does not crash.

@PKnittel, I can submit a pull request which comments out the line, but I am not sure what functionality (if any) that will break. You added this code as part of 824a2b005de95f2e01dc28a41b212d67c73d8d5, can you comment on which bug you were trying to fix here?

**Comment by shankari** [comment]
> calling open() in that case crashes the app.

on a physical device running iOS 9.

**Comment by katzer** [comment]
@linkchiu, @shankari That issue has been fixed. Thanks!
