### ISSUE TITLE
isAvailable() returns false on Android 4.4.4

### ISSUE THREAD

**Issue by thubold** [katzer/cordova-plugin-email-composer#175]
After I changed my plugins from phonegap build repository to npm, your plugin stop working for Android 4.4.4. It returns always false in the isAvailable function.
Also the open function calls the success Callback.

But thanks for your plugin and your great work :-)
Best regards Tobi

**Comment by ceskomira90** [comment]
Yes, same problem with my device. I just installed and configured various emails but isAvailable returns false! Ty in advice for your plugin.

**Comment by stephanepechard** [comment]
I'm not sure if it's exactly the same problem here. In my case, it is not particularly related to Android 4.4.4. I have tested this on Android 6.0.1 and Android 5.1.1.

Anyway, in my case `isAvailable()` never returns true because of the way accounts are validated to send mails (here: [EmailComposerImpl.java#L518](https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/android/EmailComposerImpl.java#L518)). You just test if accounts type end with `mail` but Gmail accounts have `com.google` type... The same thing happens with Yahoo! accounts.

You should probably find a better to validate mail accounts, but I have no idea how...

**Comment by shankari** [comment]
Don't want to pile on to the me-toos without adding something substantive, but I am also on Android 6.0.1 and upgrading to the most recent version of the plugin broke emailing on android.

The previous check seemed to work fine, so I looked through recent commits, and based on the comment by @stephanepechard it looks like this is the one that broke it.

https://github.com/katzer/cordova-plugin-email-composer/commit/dcb9852830bfd2b1c13009cfb18c172a72e4cc74

It looked like you didn't have any checks before and then added checks in the recent commit. Can you comment on the issue that you were trying to fix in the commit? There is no description in the commit message.

For now, I plan to remove the check from my fork and proceed. If there is interest, I can report back on the results.

**Comment by shankari** [comment]
I've made the change in my local branch, and it works. Should I submit a pull request?

**Comment by nehero** [comment]
Wouldn't hurt @shankari

**Comment by cdarken** [comment]
@shankari did you submit the pull request?

**Comment by shankari** [comment]
Nope - have been busy at work. Was planning to do so this weekend.
There's also a different pull request already submitted that solves the problem by explicitly checking for `com.google`.
https://github.com/katzer/cordova-plugin-email-composer/pull/180

Maybe the maintainers can let us know which one they prefer.

**Comment by Avi-mcqueen** [comment]
Hello,
Cant figure out what checks needs to be commented out for this to work with android.
This was working with 82 excellent and with 83 now does not.
Please help with walkaround.
Thank you

**Comment by shankari** [comment]
This is the change to comment out the check.
https://github.com/shankari/cordova-plugin-email-composer/commit/b437c5b808bfff311b59d74d8ecd23b2416059b6

Hope this helps

**Comment by Avi-mcqueen** [comment]
Thank you for help.
Did try to comment out all 'isEmailAccountConfigured' content and leave only 'return true' - did not work for me.
Returned to the 0.82 version (had a backup), works good..

**Comment by hardikthakkar3** [comment]
The problem is with isEmailAccountConfigured method in EmailComposerImpl.java

Updated code is 
private boolean isEmailAccountConfigured (Context ctx) {
        AccountManager am  = AccountManager.get(ctx);
        **Pattern emailPattern = Patterns.EMAIL_ADDRESS;**
        try {
            for (Account account : am.getAccounts()) {
                if (**emailPattern.matcher(account.name).matches()**) {
                    return true;
                }
            }
        } catch (Exception e) {
            Log.e(LOG_TAG, "Missing GET_ACCOUNTS permission.");
            return true;
        }

        return false;
    }

**Comment by Avi-mcqueen** [comment]
Thanks for the help :)

**Comment by kukikiloke** [comment]
@shankari your changes in shankari@b437c5b fixed the isAvailable always returns false but it does not fix the permission error on API level 23

**Comment by shankari** [comment]
@kukikiloke Hm - that is probably related to dynamic permissions. I am not on API 23 yet, primarily because I don't want to deal with dynamic permissions just yet, so I don't have a fix for that.
The docs on dynamic permissions are here in case anybody wants to take a look.
http://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html (scroll down to Runtime Permissions)

**Comment by katzer** [comment]
There has been some improvements to address the discussed issue. Please reopen if its still an issue with the latest version.
