### ISSUE TITLE
Windows 10 Runtime Error: module de.appplant.cordova.plugin.email-composer.EmailComposerProxy

### ISSUE THREAD

**Issue by atsats** [katzer/cordova-plugin-email-composer#190]
I have a very basic Windows 10 Cordova app with the plugin installed and I'm getting this error:

> JavaScript runtime error: module de.appplant.cordova.plugin.email-composer.EmailComposerProxy not found

The plugin is installed and it does work for both iOS and Android.  Does the plugin work under Windows 10?

**Comment by Aynolor** [comment]
In **/src/windows/EmailComposerProxyImpl.js**, try to replace :

`var proxy = require('de.appplant.cordova.plugin.email-composer.EmailComposerProxy')` 

by 

`var proxy = require('cordova-plugin-email-composer.EmailComposerProxy')`

**Comment by Mikey1982** [comment]
Thanks @Aynolor

**Comment by xFlowDev** [comment]
Is there something else that could fix this?
It just changes back to default when I run my App.

**Comment by awarenate** [comment]
I'm having this problem, also.  Any solution yet?

**Comment by stevesum** [comment]
Check the EmailComposerProxyImpl.js under /src/windows.
this should contains the following:
var proxy = require('cordova-plugin-email-composer.EmailComposerProxy'),

instead of var proxy = require('
de.appplant.cordova.plugin.email-composer.EmailComposerProxy'),

This is already fixed in the master branch, so perhaps you should only use
git pull in the plugin folder.

BR,
Steve

2017-03-27 22:26 GMT+02:00 awarenate <notifications@github.com>:
