### ISSUE TITLE
0.8.3: E-mail never gets opened on Android (callback called right away)

### ISSUE THREAD

**Issue by micschk** [katzer/cordova-plugin-email-composer#220]
The email.open action doesn't open an e-mail on 0.8.3. Instead it calls the callback right away.

``` js
            cordova.plugins.email.open(emailcontent, function () {
                console.log('e-mail action canceled');
            }, $scope);
```

On 0.8.2 the same code is working fine.

**Comment by zabojad** [comment]
I'm having the same issue. Rolling back to 0.8.2 solved it.

What happens on Android with 0.8.3 is that the [open method callback](https://github.com/katzer/cordova-plugin-email-composer#get-informed-when-the-view-has-been-dismissed) get instantly called and nothing gets opened.

**Comment by zabojad** [comment]
Hi there ! Any update on this issue?

**Comment by smika01** [comment]
Hello!
Same problem for me. Actual version didn't work on Android. Installation of version 0.8.2  as following did solve the problem for now:

cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2 

Any idea how to solve this problem in a last stable version?

Regards 
Sebastian

**Comment by rogervinas** [comment]
Version 0.8.3 checks if there is at least one email account configured. To do so the plugin needs GET_ACCOUNTS permission, I think the problem is with API level 23 this permission has to be also requested at runtime.
Try `android:targetSdkVersion="22"` in AndroidManifest.xml, worked for me!
Some of the Pull Requests fix this issue.

**Comment by micschk** [comment]
Thanks, makes sense.

Is there some configuration setting possible to skip this check? I don't
want to add 'read your accounts' to the permissions just to offer the user
a button to send an email.

Now, it seems to not work, while I'd guess 99+% of the smartphones have
e-mail automatically set up, at least on Android?

**Comment by cdebdeep** [comment]
@rogervinas 
Thanks for the update. Yes " I think the problem is with API level 23 this permission has to be requested at runtime, it does not work only adding the uses-permission in AndroidManifest.xml -- it is the main problem.
I build and debug my app connecting an android device running on API level 23 (marshmallow), i just can not send any mail. I then go to application manager of my device , find my application. Give it to Contacts permission. Now i can send mail from my application.
So, there are two points,
1. You need to give your device installed application the Contacts permission.
2. You need to have alleast one email account configured on your device. 
Thanks,
Happy Codding. :+1:

**Comment by marco-bransch** [comment]
Problem solved. Please see following fork https://github.com/starhealthcare/cordova-plugin-email-composer

**Comment by katzer** [comment]
I've added a `forceOpen` method which works like `open` however it does not care about availability of an email client, permissions granted, ... c7a9b2c
