### ISSUE TITLE
Problems with isAvailable (can't find configured email on Android)

### ISSUE THREAD

**Issue by cjs1976** [katzer/cordova-plugin-email-composer#233]
Hi,

i use this plugin for the first time. I tested it with an old Android 4 phone, and the detection worked fine: as I had noting configured, i got the right error, after i configured the phone, everything worked. Then I sent my app to some friends (new Android Phones), and they get always the error that no email is available/configured. But it is.

In the issues I found some posts with the same problem, but there seems to be no solution so far. Most of them say, go back to version 0.8.2. But is this a good solution?

Thanks,
Christian.

**Comment by naoned44** [comment]
I had the same issue. The problem is that the mail account is not detected in system, only in the app
That can be solved by changing the canSendMail test in EmailComposerImpl.java.
I changed
return new boolean[] { isPossible, withScheme };
by
return new boolean[] { withScheme, withScheme };

So the test is only on available mail apps, not on the account. 

Hope it help

**Comment by cjs1976** [comment]
@naoned44 Thank's for this hint, but I changed already to another plugin.

**Comment by seopei** [comment]
PR #245 will fix this
sdk's >= 23 need runtime permissions
