### ISSUE TITLE
Attach a file created with cordova 3.3 or 3.4

### ISSUE THREAD

**Issue by sebastianperrone** [katzer/cordova-plugin-email-composer#33]
Hello, I am using your plugin to send a mail with some data. Now I need to attach a file and I am a little lost on how to do it consistently for iOS and android. In android, I create a file to store it in persistent file system (ie: /myApFileSystem/test.pdf), to include in attachments array structure I must prefix with "absolute://sdcard/", this works fine, but in ios I cannot know (at least I do not notice) the absolute file path (see https://github.com/apache/cordova-plugin-file/blob/master/doc/index.md). I try with relative prefix but I cannot get the right way to do it (I try 'relative://myApFileSystem/test.pdf'). 
Can you guide me on how to set the string path for attachments ?

**Comment by superdude387** [comment]
Has the file path syntax changed since this was last commented? I cannot seem to get my file to attach no matter which file path I try. I've spent most of today trying to get my pdf to attach to the email, and in the composer view it shows the correct file name attached, however once it is sent, the file is not truly attached. Any help?

**Comment by cepm-nate** [comment]
I'm using myFile.toURL() and am also having a horrible time. 

on iOS, the file ends up in the email with the right filename, but is only 625 bytes instead of a couple hundred KB.

on Android, I'm constantly getting 'Permission Denied' with the attachment when the email window opens. I've tried storing in cordova.file.dataDirectory and in cordova.file.cacheDirectory.

Situation: I'm download a PDF from a server, then trying to attach it to an e-mail.

Is there some cross-platform place (cordova.file.xxxxx) to store files that can be accessed outside the app? Presumably this would fix both issues.
